### ISSUE TITLE
Bug:  alert user if Badge image is not B&W

### ISSUE THREAD

**Issue by boyofgreen** [pwa-builder/ManifoldJS#233]

**Comment by marcoscaceres** [comment]
Just FYI, we added `{"purpose":  "badge"}` to image objects in the manifest spec. Details and example: https://www.w3.org/TR/appmanifest/#purpose-member

**Comment by boyofgreen** [comment]
Thanks Marcos.  We'll watch this, it will be helpful for the badges.   @mconverti lets keep our eye on this.
