### ISSUE TITLE
Discrepancy between manifest validation in step 1 and step 3

### ISSUE THREAD

**Issue by wvmstr** [pwa-builder/ManifoldJS#281]
In step 1 of the PWA builder I get warnings (0) and suggestions (0).

In step 3:

"There are some validation errors in the manifest. Please fix them and try again."

When I do the validation with the Chrome plugin called "Lighthouse"  I get a score of 91, with the only failure being: 

"User will not be prompted to Install the Web App Failures: Manifest start_url is not cached by a Service Worker."

**Comment by boyofgreen** [comment]
see the other issue there:  https://github.com/pwa-builder/manifoldjs-windows10/issues/25 and let me know if you have any questions.
  I'm going to leave this issue open as we need to either not validate against that (need to compare to spec) or bubble the right errors up.

**Comment by boyofgreen** [comment]
fixed in preview
