### ISSUE TITLE
[Question] excluding/including directories/files

### ISSUE THREAD

**Issue by meinbrodt** [pwa-builder/ManifoldJS#290]
Hello, 

just one question:

Is it possible to exclude directories/files from the created package (e.g. a hidden .git folder, a node_modules folder etc.) or to specifically define which directories/files should be part of the created package? 

Best regards and thanks, Matthias

**Comment by boyofgreen** [comment]
Hi @meinbrodt   is this for a traditional PWA or were you asking about an edge extension?
