### ISSUE TITLE
StatusBar color

### ISSUE THREAD

**Issue by urkh** [pwa-builder/ManifoldJS#298]
How can i change the status bar color? 

I have modified theme_color and background_color on manifest.json and didn't work

[https://imgur.com/a/l8MlW](https://imgur.com/a/l8MlW)

Thanks

**Comment by boyofgreen** [comment]
so for right now that is a WinRT API, but we are looking to address that in windows in next version.  See an example here:  
https://github.com/boyofgreen/pixiebob/blob/newtest/default.html#L64
