### ISSUE TITLE
how can i use cordova plugin in my hosted web app?

### ISSUE THREAD

**Issue by ShuiShengYe** [pwa-builder/ManifoldJS#299]
I create a cordova hosted web app. It uses geolocation, and i want that it loads pages from server.
how can i do it.

**Comment by boyofgreen** [comment]
hello ShuiShengYe!  we have a doc for that...  https://github.com/pwa-builder/ManifoldJS/wiki/Using-Cordova-Plugins-in-Hosted-Web-Apps
