### ISSUE TITLE
PWA Angular.js & Cordova plugins

### ISSUE THREAD

**Issue by uzijsalem** [pwa-builder/ManifoldJS#309]
Hi,

I am currently trying to build a pwa app. I want to inject some cordova plugin in client mode. I followed the tutorial to show a notification but nothing happened. I will like to know if on my server side I have to do some configurations to allow the plugin injection.

**Comment by boyofgreen** [comment]
Hi @uzijsalem sorry for the late replay, but we are depricating the cordova portion of the apps, we recommend you use the cordova tool directly after you generate a PWA if you would like to continue using plugins.
