### ISSUE TITLE
Cordova isn't building my manifoldJS project

### ISSUE THREAD

**Issue by mattwoberts** [pwa-builder/ManifoldJS#310]
I built an app using ManifoldJS about 18 months ago, and it's working well for me.

However, nothing stands still in mobile apps, so I've come back to update things, and make a number of changes. 

I've updated my manifold file, and run `cordova build ios` to compile this, but it's not working any more. The output I get is:

```
Updating Cordova configuration from W3C manifest...
The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.
Error: Cannot find module '../../node_modules/elementtree'
```

It's worth mentioning that this a new mac. I've installed cordova 8.0.0. I un-installed that and downgraded to 7.1.0 (I think that's the version I used to use), but again I get the same output.

I can't see a packages.json that defines which node modules it might need, so I'm overall a bit confused - any assistance would be helpful!

**Comment by mattwoberts** [comment]
Just to sanity-test this, I just installed and test ran "pwabuilder" to generate a new site - with the same error. Here's what I did:

```
npm install -g pwabuilder
pwabuilder https://www.bbc.co.uk -d bbcapp -l info -p ios,android
(cd into project)
cordova build ios
```

and the output:

```
Updating Cordova configuration from W3C manifest...
The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.
Error: Cannot find module '../../node_modules/elementtree'
```

**Comment by mattwoberts** [comment]
@boyofgreen Would love if you could cast your eyes over this - it seems very quiet in here :)

**Comment by boyofgreen** [comment]
hey Matt.
  I'm going to go ahead a close this issue as we can track it with the issue open in the manifold-cordova project.  As mentioned there, I'm looking for someone to address it!
