### ISSUE TITLE
Android version and phonegap-plugin-push

### ISSUE THREAD

**Issue by FranceJ** [pwa-builder/ManifoldJS#312]
The latest versions of several cordova plugins, in this case [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push), require a more recent cordova-android version than 5.1.1.

For many apps downgrading is a good option, but for phonegap-plugin-push specifically using at least 2.x.x is important. Version 2 supports FCM instead of GCM and as GCM is being deprecated next year it is important to be on this version. Also, even version one requires and android version of 6.0.0.

Are there any plans to upgrade to the most recent version of cordova-android soon? If not, are there any recommendations for how to deal with FCM using PWABuilder?

**Comment by boyofgreen** [comment]
Hi @FranceJ . We are actually moving away from the cordova version, and will be releasing a new (simpler) android platform: https://github.com/pwa-builder/pwabuilder-android   
   I'm hoping to get that up within the next two weeks, but you can try it by adding it as a platform within the CLI.

**Comment by boyofgreen** [comment]
@FranceJ  just a heads up,  considering we don't have a great alternative for iOS yet, we are going to do one more upgrade to the manifold-cordova package to bring it up to the most recent version of cordova.
