### ISSUE TITLE
pwabuilder  -m src/manifest.json -p windows10,android,ios  command returns this.. any help???

### ISSUE THREAD

**Issue by abhinav-official** [pwa-builder/ManifoldJS#314]
[error] pwabuilder  : Failed to create the Cordova Platform app.
                      Failed to add one or more plugins.
                      External process [process ID: 7888] completed with errors. The system cannot find the file specified.
[error] pwabuilder  : One or more platforms could not be generated successfully.
                      For more information, run pwabuilder with the diagnostics level set to debug (e.g. pwabuilder [...] -l debug)

**Comment by boyofgreen** [comment]
hi @abhinav-official  we are doing one last update to the cordova platform in the next few weeks, after that we'll ask everyone to move to our new android platform
